In [1]:
pip install pandas numpy matplotlib seaborn sqlalchemy

Requirement already satisfied: pandas in c:\users\home\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\home\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\home\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\home\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: sqlalchemy in c:\users\home\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\home\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\home\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\home\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\home\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\home\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\home\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\home\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\home\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\home\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\home\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: greenlet>=1 in c:\users\home\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\home\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\home\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os

In [3]:
files = glob.glob("../data/raw/amazon_india_*.csv")

transaction_files = [
    file for file in files
    if "products_catalog" not in file
]

df_list = []

for file in transaction_files:
    df = pd.read_csv(file)
    df_list.append(df)

transactions = pd.concat(df_list, ignore_index=True)

print(transactions.shape)
transactions.head()

(1127609, 34)

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,"21,947.26",0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,FALSE,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1

In [4]:
products = pd.read_csv("../data/raw/amazon_india_products_catalog.csv")

print(products.shape)
products.head()

(2004, 11)

,product_id,product_name,category,subcategory,brand,base_price_2015,weight_kg,rating,is_prime_eligible,launch_year,model
0,PROD_000001,Apple iPhone 6 16GB Black,Electronics,Smartphones,Apple,190469.10,0.21,3.9,True,2015,iPhone 6
1,PROD_000002,Apple iPhone 6 32GB Black,Electronics,Smartphones,Apple,158424.89,0.18,3.4,True,2015,iPhone 6
2,PROD_000003,Apple iPhone 6 64GB Black,Electronics,Smartphones,Apple,118141.16,0.22,4.6,True,2015,iPhone 6
3,PROD_000004,Apple iPhone 6 16GB White,Electronics,Smartphones,Apple,211721.16,0.21,4.1,True,2015,iPhone 6
4,PROD_000005,Apple iPhone 6 32GB White,Electronics,Smartphones,Apple,114806.24,0.20,3.8,True,2015,iPhone 6

In [5]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127609 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1127609 non-null  object
 1   order_date              1127609 non-null  object
 2   customer_id             1127609 non-null  object
 3   product_id              1127609 non-null  object
 4   product_name            1127609 non-null  object
 5   category                1127609 non-null  object
 6   subcategory             1127609 non-null  object
 7   brand                   1127609 non-null  object
 8   original_price_inr      1127609 non-null  object
 9   discount_percent        1127609 non-null  float64
 10  discounted_price_inr    1127609 non-null  float64
 11  quantity                1127609 non-null  int64
 12  subtotal_inr            1127609 non-null  float64
 13  delivery_charges        1037408 non-null  float64
 14  final_amount_inr        1127609 non-null  float64
 15  customer_city           1127609 non-null  object
 16  customer_state          1127609 non-null  object
 17  customer_tier           1127609 non-null  object
 18  customer_spending_tier  1127609 non-null  object
 19  customer_age_group      992294 non-null   object
 20  payment_method          1127609 non-null  object
 21  delivery_days           1127609 non-null  object
 22  delivery_type           1127609 non-null  object
 23  is_prime_member         1127609 non-null  object
 24  is_festival_sale        1127609 non-null  object
 25  festival_name           349873 non-null   object
 26  customer_rating         785913 non-null   object
 27  return_status           1127609 non-null  object
 28  order_month             1127609 non-null  int64
 29  order_year              1127609 non-null  int64
 30  order_quarter           1127609 non-null  int64
 31  product_weight_kg       1127609 non-null  float64
 32  is_prime_eligible       1127609 non-null  object
 33  product_rating          1127609 non-null  float64
dtypes: float64(7), int64(4), object(23)
memory usage: 292.5+ MB

In [6]:
transactions.describe()

,discount_percent,discounted_price_inr,quantity,subtotal_inr,delivery_charges,final_amount_inr,order_month,order_year,order_quarter,product_weight_kg,product_rating
count,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.037408e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06
mean,1.742035e+01,5.454134e+04,1.250063e+00,6.818740e+04,3.084611e-04,6.818740e+04,6.940627e+00,2.020637e+03,2.645922e+00,7.806976e-01,3.975245e+00
std,2.055377e+01,4.582480e+04,5.365034e-01,6.893407e+04,1.110782e-01,6.893407e+04,3.539183e+00,2.690906e+00,1.140795e+00,3.674216e+00,4.536469e-01
min,0.000000e+00,3.443300e+02,1.000000e+00,3.443300e+02,0.000000e+00,3.443300e+02,1.000000e+00,2.015000e+03,1.000000e+00,3.000000e-02,3.000000e+00
25%,0.000000e+00,2.278069e+04,1.000000e+00,2.521799e+04,0.000000e+00,2.521799e+04,4.000000e+00,2.019000e+03,2.000000e+00,1.800000e-01,3.600000e+00
50%,1.037000e+01,3.800119e+04,1.000000e+00,4.473182e+04,0.000000e+00,4.473182e+04,7.000000e+00,2.021000e+03,3.000000e+00,2.100000e-01,4.000000e+00
75%,2.841000e+01,7.410332e+04,1.000000e+00,8.852179e+04,0.000000e+00,8.852179e+04,1.000000e+01,2.023000e+03,4.000000e+00,2.400000e-01,4.400000e+00
max,7.000000e+01,4.207048e+05,3.000000e+00,1.262114e+06,4.000000e+01,1.262114e+06,1.200000e+01,2.025000e+03,4.000000e+00,4.426000e+01,4.800000e+00

In [7]:
transactions.columns.tolist()

['transaction_id',
 'order_date',
 'customer_id',
 'product_id',
 'product_name',
 'category',
 'subcategory',
 'brand',
 'original_price_inr',
 'discount_percent',
 'discounted_price_inr',
 'quantity',
 'subtotal_inr',
 'delivery_charges',
 'final_amount_inr',
 'customer_city',
 'customer_state',
 'customer_tier',
 'customer_spending_tier',
 'customer_age_group',
 'payment_method',
 'delivery_days',
 'delivery_type',
 'is_prime_member',
 'is_festival_sale',
 'festival_name',
 'customer_rating',
 'return_status',
 'order_month',
 'order_year',
 'order_quarter',
 'product_weight_kg',
 'is_prime_eligible',
 'product_rating']

In [8]:
transactions.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,"21,947.26",0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,FALSE,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1

In [9]:
transactions.isnull().sum().sort_values(ascending=False)

festival_name             777736
customer_rating           341696
customer_age_group        135315
delivery_charges           90201
product_weight_kg              0
order_quarter                  0
order_year                     0
order_month                    0
return_status                  0
customer_spending_tier         0
is_prime_eligible              0
is_festival_sale               0
is_prime_member                0
delivery_type                  0
delivery_days                  0
payment_method                 0
transaction_id                 0
customer_tier                  0
order_date                     0
customer_state                 0
customer_city                  0
final_amount_inr               0
subtotal_inr                   0
quantity                       0
discounted_price_inr           0
discount_percent               0
original_price_inr             0
brand                          0
subcategory                    0
category                       0
product_name                   0
product_id                     0
customer_id                    0
product_rating                 0
dtype: int64

In [10]:
transactions.duplicated().sum()

np.int64(0)

In [11]:
transactions["category"].value_counts()

category
Electronics                  1126726
Electronic                       229
ELECTRONICS                      225
Electronics & Accessories        218
Electronicss                     211
Name: count, dtype: int64

In [12]:
transactions["payment_method"].value_counts()

payment_method
UPI            384228
COD            322831
Credit Card    172261
Debit Card     140202
Net Banking     64971
Wallet          22821
BNPL            20295
Name: count, dtype: int64

In [13]:
transactions["customer_city"].value_counts().head(30)

customer_city
Mumbai           140536
Delhi            122365
Bangalore        101416
Chennai           83646
Pune              67703
Kolkata           65767
Ahmedabad         50861
Hyderabad         44573
Jaipur            40453
Surat             40400
Nagpur            37211
Kanpur            34334
Lucknow           34077
Indore            33592
Coimbatore        26695
Kochi             24940
Visakhapatnam     22167
Patna             21339
Vadodara          21078
Bhubaneswar       20472
Chandigarh        19575
Ludhiana          18891
Saharanpur         6705
Meerut             6641
Bareilly           6590
Aligarh            6407
Allahabad          6030
Varanasi           5897
Gorakhpur          5867
Moradabad          5855
Name: count, dtype: int64

In [14]:
transactions["delivery_days"].unique()[:30]

array(['6', '4', '3', '5', '7', 'Express', '0', '-1', 'Same Day',
       '1-2 days', '15', '1', '2'], dtype=object)

In [15]:
transactions["customer_rating"].unique()[:30]

array(['5.0', '4.5', nan, '3.0', '4.0', '3.5', '4/5', '5.0 stars',
       '5.0/5.0', '4.5 stars', '3.5/5.0', '3/5', '4', '4.0 stars',
       '4.5/5.0', '5', '5/5', '4.0/5.0', '3.5 stars', '3.0 stars', '3',
       '3.0/5.0'], dtype=object)

In [16]:
#Challenge 1: Date Standardization
transactions["order_date"] = pd.to_datetime(
    transactions["order_date"],
    errors="coerce"
)

transactions["order_date"].isna().sum()

np.int64(108256)

In [17]:
#Challenge 2: Price Cleaning
price_cols = [
    "original_price_inr",
    "discounted_price_inr",
    "subtotal_inr",
    "final_amount_inr"
]

for col in price_cols:
    if col in transactions.columns:
        transactions[col] = (
            transactions[col]
            .astype(str)
            .str.replace("₹", "", regex=False)
            .str.replace(",", "", regex=False)
            .str.replace("Price on Request", "", regex=False)
            .str.strip()
        )

        transactions[col] = pd.to_numeric(
            transactions[col],
            errors="coerce"
        )

        transactions[col] = transactions[col].fillna(
            transactions[col].median()
        )

In [18]:
#Challenge 3: Customer Rating Standardization
transactions["customer_rating"] = (
    transactions["customer_rating"]
    .astype(str)
    .str.extract(r"(\d+\.?\d*)")[0]
)

transactions["customer_rating"] = pd.to_numeric(
    transactions["customer_rating"],
    errors="coerce"
)

transactions.loc[
    (transactions["customer_rating"] < 1) |
    (transactions["customer_rating"] > 5),
    "customer_rating"
] = np.nan

transactions["customer_rating"] = transactions["customer_rating"].fillna(
    transactions["customer_rating"].median()
)

In [19]:
#Challenge 4: City Standardization
transactions["customer_city"] = (
    transactions["customer_city"]
    .astype(str)
    .str.strip()
    .str.title()
)

city_map = {
    "Bombay": "Mumbai",
    "Bangalore": "Bengaluru",
    "New Delhi": "Delhi",
    "Delihi": "Delhi",
    "Hydrabad": "Hyderabad",
    "Chennaii": "Chennai",
    "Kolkatta": "Kolkata"
}

transactions["customer_city"] = transactions["customer_city"].replace(city_map)

In [22]:
#Challenge 5: Boolean Standardization

bool_map = {
    "Yes": True,
    "No": False,
    "Y": True,
    "N": False,
    "TRUE": True,
    "FALSE": False,
    "True": True,
    "False": False,
    "1": True,
    "0": False,
    1: True,
    0: False
}

for col in ["is_prime_member", "is_festival_sale"]:
    if col in transactions.columns:
        transactions[col] = transactions[col].replace(bool_map)

In [23]:
# Challenge 6: Category Standardization

transactions["category"] = (
    transactions["category"]
    .astype(str)
    .str.strip()
    .str.title()
)

category_map = {
    "Electronic": "Electronics",
    "Electronics & Accessories": "Electronics",
    "Electronics Accessories": "Electronics",
    "Fashion & Apparel": "Fashion",
    "Home And Kitchen": "Home & Kitchen"
}

transactions["category"] = transactions["category"].replace(category_map)

transactions["category"].value_counts()

category
Electronics     1127398
Electronicss        211
Name: count, dtype: int64

In [24]:
# Challenge 7: Delivery Days Cleaning

transactions["delivery_days"] = (
    transactions["delivery_days"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)

transactions["delivery_days"] = pd.to_numeric(
    transactions["delivery_days"],
    errors="coerce"
)

transactions.loc[
    (transactions["delivery_days"] < 0) |
    (transactions["delivery_days"] > 30),
    "delivery_days"
] = np.nan

transactions["delivery_days"] = transactions["delivery_days"].fillna(
    transactions["delivery_days"].median()
)

transactions["delivery_days"].describe()

count    1.127609e+06
mean     3.331342e+00
std      1.748076e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      1.500000e+01
Name: delivery_days, dtype: float64

In [25]:
# Challenge 8: Duplicate Transaction Handling

duplicates_before = transactions.duplicated().sum()

transactions = transactions.drop_duplicates()

duplicates_after = transactions.duplicated().sum()

print("Before:", duplicates_before)
print("After:", duplicates_after)

Before: 0
After: 0

In [26]:
# Challenge 9: Price Outlier Detection

Q1 = transactions["final_amount_inr"].quantile(0.25)
Q3 = transactions["final_amount_inr"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

transactions["price_outlier_flag"] = (
    (transactions["final_amount_inr"] < lower_limit) |
    (transactions["final_amount_inr"] > upper_limit)
)

print(
    transactions["price_outlier_flag"].value_counts()
)

price_outlier_flag
False    1060033
True       67576
Name: count, dtype: int64

In [27]:
# Challenge 10: Payment Method Standardization

transactions["payment_method"] = (
    transactions["payment_method"]
    .astype(str)
    .str.upper()
    .str.strip()
)

payment_map = {
    "PHONEPE": "UPI",
    "GOOGLEPAY": "UPI",
    "GOOGLE PAY": "UPI",
    "GPAY": "UPI",

    "CC": "CREDIT CARD",
    "CREDIT_CARD": "CREDIT CARD",

    "C.O.D": "COD",
    "CASH ON DELIVERY": "COD"
}

transactions["payment_method"] = (
    transactions["payment_method"]
    .replace(payment_map)
)

transactions["payment_method"].value_counts()

payment_method
UPI            384228
COD            322831
CREDIT CARD    172261
DEBIT CARD     140202
NET BANKING     64971
WALLET          22821
BNPL            20295
Name: count, dtype: int64

In [28]:
transactions["payment_method"].unique()

array(['COD', 'DEBIT CARD', 'CREDIT CARD', 'NET BANKING', 'UPI', 'WALLET',
       'BNPL'], dtype=object)

In [29]:
print("Dataset Shape:", transactions.shape)

print("\nMissing Values:")
print(transactions.isnull().sum().sort_values(ascending=False))

print("\nDuplicate Rows:")
print(transactions.duplicated().sum())

print("\nPayment Methods:")
print(transactions["payment_method"].value_counts())

print("\nCategories:")
print(transactions["category"].value_counts())

print("\nCustomer Ratings:")
print(transactions["customer_rating"].describe())

print("\nDelivery Days:")
print(transactions["delivery_days"].describe())

Dataset Shape: (1127609, 35)

Missing Values:
festival_name             777736
customer_age_group        135315
order_date                108256
delivery_charges           90201
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
transaction_id                 0
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
customer_rating                0
customer_tier                  0
customer_spending_tier         0
customer_state                 0
customer_city                  0
final_amount_inr               0
subtotal_inr                   0
quantity                       0
discounted_price_inr           0
discount_percent               0
original_price_inr             0
brand                          0
subcategory                    0
category                       0
product_name                   0
product_id                     0
customer_id                    0
price_outlier_flag             0
dtype: int64

Duplicate Rows:
0

Payment Methods:
payment_method
UPI            384228
COD            322831
CREDIT CARD    172261
DEBIT CARD     140202
NET BANKING     64971
WALLET          22821
BNPL            20295
Name: count, dtype: int64

Categories:
category
Electronics     1127398
Electronicss        211
Name: count, dtype: int64

Customer Ratings:
count    1.127609e+06
mean     4.368098e+00
std      4.857911e-01
min      3.000000e+00
25%      4.000000e+00
50%      4.500000e+00
75%      4.500000e+00
max      5.000000e+00
Name: customer_rating, dtype: float64

Delivery Days:
count    1.127609e+06
mean     3.331342e+00
std      1.748076e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      1.500000e+01
Name: delivery_days, dtype: float64

In [30]:
# Save Cleaned Dataset

os.makedirs("../data/cleaned", exist_ok=True)

transactions.to_csv(
    "../data/cleaned/cleaned_transactions.csv",
    index=False
)

products.to_csv(
    "../data/cleaned/cleaned_products.csv",
    index=False
)

print("Data cleaning completed successfully.")

Data cleaning completed successfully.

In [31]:
transactions["category"].value_counts()

category
Electronics     1127398
Electronicss        211
Name: count, dtype: int64

In [32]:
transactions["category"] = (
    transactions["category"]
    .astype(str)
    .str.strip()
    .str.title()
)

transactions["category"] = transactions["category"].replace({
    "Electronic": "Electronics",
    "Electronicss": "Electronics",
    "Electronics & Accessories": "Electronics"
})

In [38]:
import os

os.makedirs("../data/cleaned", exist_ok=True)

transactions.to_csv(
    "../data/cleaned/cleaned_transactions.csv",
    index=False
)

products.to_csv(
    "../data/cleaned/cleaned_products.csv",
    index=False
)

print("Data cleaning saved successfully")

Data cleaning saved successfully

In [39]:
print(os.listdir("../data/cleaned"))

['.ipynb_checkpoints', 'cleaned_products.csv', 'cleaned_transactions.csv']